Add s

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -1,21 +1,3 @@
-###########################################################
-################# General Shell Shortcuts ##################
-############################################################
-
-# source .zshrc
-alias sz='source ~/.zshrc && echo "sourced ~/.zshrc successfully"'
-
-# edit .zshrc
-alias ez='vi ~/.zshrc && sz'
-
-# edit .aliases
-alias ea='vi ~/.aliases'
-
-alias ls='ls -G'
-
-# List all files colorized in long format, including dot files
-alias la="ls -lha"
-
 
 ############################################################
 ###################### Random Helpers ######################
@@ -160,27 +142,34 @@ help() {
 
 # use scmpuff numbering for other commands
 # eg: `s rm 2-3`
-s() {
+cm() {
   local cmd=$1
   shift
 
-  # Get file list from scmpuff
-  local files
-  IFS=$'\n' read -d '' -r -a files < <(scmpuff status --filelist && printf '\0')
+  # Get scmpuff-style indexed files into array
+  local raw_files
+  raw_files=$(scmpuff status --filelist)
+  local -a files
+  files=("${(f)raw_files}")
 
-  # Expand arguments
-  local expanded=()
+  # Build expanded list of arguments
+  local -a expanded
   for arg in "$@"; do
-    if [[ "$arg" =~ ^[0-9]+$ ]]; then
-      index=$((arg - 1))
-      expanded+=("${files[$index]}")
+    if [[ "$arg" =~ '^[0-9]+$' ]]; then
+      local index=$((arg - 1))
+      if [[ -n "${files[$index]}" ]]; then
+        expanded+=("${files[$index]}")
+      else
+        echo "Invalid index: $arg" >&2
+        return 1
+      fi
     else
       expanded+=("$arg")
     fi
   done
 
   echo "▶ $cmd ${expanded[*]}"
-  $cmd "${expanded[@]}"
+  command "$cmd" "${expanded[@]}"
 }
 
 # cocoapods
